name: nyc-taxi-pipeline

schedule: daily

start_date: "2022-01-01"

default_connections:
  duckdb: duckdb-default

variables:
  taxi_types:
    type: array  # should be: array
    items:
      type: string  # should be: string
    default: ["yellow"]  # e.g. ["yellow", "green"]
